version: "3.9"
services:
  consumer:
    build: consumer
    depends_on:
      - provider
    ports:
      - "8080:8080"
    environment:
      - NacosAddr=127.0.0.1:8848
      - NacosNamespace=dev
    command: [ "/app/main" ]

  provider:
    build: provider
    ports:
      - "8081:8081"
    environment:
      - NacosAddr=127.0.0.1:8848
      - NacosNamespace=dev
    command: [ "/app/main" ]